### ISSUE TITLE
add Gradio Web Demo for cvpr 2022 call for demos

### ISSUE THREAD

**Issue by AK391** [dineshreddy91/WALT#1]
Hi, would you be interested in adding WALT to Hugging Face as a Gradio Web Demo for CVPR 2022 call for Demos? The Hub offers free hosting, and it would make your work more accessible and visible to the rest of the ML community. Models/datasets/spaces(web demos) can be added to a user account or organization similar to github.

more info on CVPR call for demos: https://huggingface.co/CVPR

and here are guides for adding web demo to the org

How to add a Space: https://huggingface.co/blog/gradio-spaces

Please let us know if you would be interested and if you have any questions, we can also help with the technical implementation.

**Comment by dineshreddy91** [comment]
Hi, thanks for the comment. I would be happy to make a demo. I have just finished the final version of the code. Let me know how to integrate it with HuggingFace

**Comment by AK391** [comment]
@dineshreddy91 great, you can join the organization here: https://huggingface.co/organizations/CVPR/share/RjqpcpbHuMUTqHAbHJcaKIvgrHurkBipkQ and add the gradio demo by following the steps in the organization card or the tutorial here: https://huggingface.co/blog/gradio-spaces. Also here is a example Gradio Demo: https://huggingface.co/spaces/CVPR/ml-talking-face, thanks!

**Comment by dineshreddy91** [comment]
Demo added to readme
