### ISSUE TITLE
In  line 113 Clip_WALT_Generate.py, the stationary_obj is always []

### ISSUE THREAD

**Issue by CarolynXzy** [dineshreddy91/WALT#2]
Hello, I working on amodal instance segmentation task, and I follow your paper WALT. I can't run out the function get_unoccluded_instances, and get the return stationary_obj. It would be great if you could solve my problem.

**Comment by dineshreddy91** [comment]
If stationary_obj is [] means that we could not find any objects in the same location which are stationary. That should not block you from running this code. The unoccluded object instances do not need this parameter.

**Comment by CarolynXzy** [comment]
I mean stationary_obj is always [], even though have a  stationary object. And the for loop in line 80 to line 96 in Clip_WALT_Generate.py will never be executed. I download your code and check the cam2.json_stationary.npz is [] too.

**Comment by dineshreddy91** [comment]
The stationary object code will not work in the case of cam2 is because the time difference between frames is large. For the stationary object detection to work you need to give a continuous video and change line 78 to

if [time.year,time.month, time.day, time.hour] in time_checked:

**Comment by CarolynXzy** [comment]
Thank you
